services:
  anki-desktop:
    image: mlcivilengineer/anki-desktop-docker:main
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./anki_data:/config
    ports:
      - 3000:3000  # Web UI
      - 8765:8765  # AnkiConnect
